/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as VerifyFaceRouteImport } from './routes/verify-face'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LockRouteImport } from './routes/lock'
import { Route as HuddleRouteImport } from './routes/huddle'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BreakGlassRouteImport } from './routes/break-glass'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VouchVoteIdRouteImport } from './routes/vouch.$voteId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyFaceRoute = VerifyFaceRouteImport.update({
  id: '/verify-face',
  path: '/verify-face',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const HuddleRoute = HuddleRouteImport.update({
  id: '/huddle',
  path: '/huddle',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakGlassRoute = BreakGlassRouteImport.update({
  id: '/break-glass',
  path: '/break-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VouchVoteIdRoute = VouchVoteIdRouteImport.update({
  id: '/vouch/$voteId',
  path: '/vouch/$voteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/break-glass': typeof BreakGlassRoute
  '/contact': typeof ContactRoute
  '/friends': typeof FriendsRoute
  '/huddle': typeof HuddleRoute
  '/lock': typeof LockRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/telemetry': typeof TelemetryRoute
  '/verify-face': typeof VerifyFaceRoute
  '/videos': typeof VideosRoute
  '/waitlist': typeof WaitlistRoute
  '/api/chat': typeof ApiChatRoute
  '/vouch/$voteId': typeof VouchVoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/break-glass': typeof BreakGlassRoute
  '/contact': typeof ContactRoute
  '/friends': typeof FriendsRoute
  '/huddle': typeof HuddleRoute
  '/lock': typeof LockRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/telemetry': typeof TelemetryRoute
  '/verify-face': typeof VerifyFaceRoute
  '/videos': typeof VideosRoute
  '/waitlist': typeof WaitlistRoute
  '/api/chat': typeof ApiChatRoute
  '/vouch/$voteId': typeof VouchVoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/break-glass': typeof BreakGlassRoute
  '/contact': typeof ContactRoute
  '/friends': typeof FriendsRoute
  '/huddle': typeof HuddleRoute
  '/lock': typeof LockRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/telemetry': typeof TelemetryRoute
  '/verify-face': typeof VerifyFaceRoute
  '/videos': typeof VideosRoute
  '/waitlist': typeof WaitlistRoute
  '/api/chat': typeof ApiChatRoute
  '/vouch/$voteId': typeof VouchVoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/break-glass'
    | '/contact'
    | '/friends'
    | '/huddle'
    | '/lock'
    | '/login'
    | '/partner'
    | '/rooms'
    | '/settings'
    | '/sitemap.xml'
    | '/team'
    | '/telemetry'
    | '/verify-face'
    | '/videos'
    | '/waitlist'
    | '/api/chat'
    | '/vouch/$voteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/break-glass'
    | '/contact'
    | '/friends'
    | '/huddle'
    | '/lock'
    | '/login'
    | '/partner'
    | '/rooms'
    | '/settings'
    | '/sitemap.xml'
    | '/team'
    | '/telemetry'
    | '/verify-face'
    | '/videos'
    | '/waitlist'
    | '/api/chat'
    | '/vouch/$voteId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/break-glass'
    | '/contact'
    | '/friends'
    | '/huddle'
    | '/lock'
    | '/login'
    | '/partner'
    | '/rooms'
    | '/settings'
    | '/sitemap.xml'
    | '/team'
    | '/telemetry'
    | '/verify-face'
    | '/videos'
    | '/waitlist'
    | '/api/chat'
    | '/vouch/$voteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  BreakGlassRoute: typeof BreakGlassRoute
  ContactRoute: typeof ContactRoute
  FriendsRoute: typeof FriendsRoute
  HuddleRoute: typeof HuddleRoute
  LockRoute: typeof LockRoute
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  RoomsRoute: typeof RoomsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  TelemetryRoute: typeof TelemetryRoute
  VerifyFaceRoute: typeof VerifyFaceRoute
  VideosRoute: typeof VideosRoute
  WaitlistRoute: typeof WaitlistRoute
  ApiChatRoute: typeof ApiChatRoute
  VouchVoteIdRoute: typeof VouchVoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-face': {
      id: '/verify-face'
      path: '/verify-face'
      fullPath: '/verify-face'
      preLoaderRoute: typeof VerifyFaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huddle': {
      id: '/huddle'
      path: '/huddle'
      fullPath: '/huddle'
      preLoaderRoute: typeof HuddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/break-glass': {
      id: '/break-glass'
      path: '/break-glass'
      fullPath: '/break-glass'
      preLoaderRoute: typeof BreakGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vouch/$voteId': {
      id: '/vouch/$voteId'
      path: '/vouch/$voteId'
      fullPath: '/vouch/$voteId'
      preLoaderRoute: typeof VouchVoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  BreakGlassRoute: BreakGlassRoute,
  ContactRoute: ContactRoute,
  FriendsRoute: FriendsRoute,
  HuddleRoute: HuddleRoute,
  LockRoute: LockRoute,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  RoomsRoute: RoomsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  TelemetryRoute: TelemetryRoute,
  VerifyFaceRoute: VerifyFaceRoute,
  VideosRoute: VideosRoute,
  WaitlistRoute: WaitlistRoute,
  ApiChatRoute: ApiChatRoute,
  VouchVoteIdRoute: VouchVoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
