/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LockRouteImport } from './routes/lock'
import { Route as HuddleRouteImport } from './routes/huddle'
import { Route as BreakGlassRouteImport } from './routes/break-glass'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VouchVoteIdRouteImport } from './routes/vouch.$voteId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const HuddleRoute = HuddleRouteImport.update({
  id: '/huddle',
  path: '/huddle',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakGlassRoute = BreakGlassRouteImport.update({
  id: '/break-glass',
  path: '/break-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VouchVoteIdRoute = VouchVoteIdRouteImport.update({
  id: '/vouch/$voteId',
  path: '/vouch/$voteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/break-glass': typeof BreakGlassRoute
  '/huddle': typeof HuddleRoute
  '/lock': typeof LockRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/api/chat': typeof ApiChatRoute
  '/vouch/$voteId': typeof VouchVoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/break-glass': typeof BreakGlassRoute
  '/huddle': typeof HuddleRoute
  '/lock': typeof LockRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/api/chat': typeof ApiChatRoute
  '/vouch/$voteId': typeof VouchVoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/break-glass': typeof BreakGlassRoute
  '/huddle': typeof HuddleRoute
  '/lock': typeof LockRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/api/chat': typeof ApiChatRoute
  '/vouch/$voteId': typeof VouchVoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/break-glass'
    | '/huddle'
    | '/lock'
    | '/login'
    | '/sitemap.xml'
    | '/team'
    | '/api/chat'
    | '/vouch/$voteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/break-glass'
    | '/huddle'
    | '/lock'
    | '/login'
    | '/sitemap.xml'
    | '/team'
    | '/api/chat'
    | '/vouch/$voteId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/break-glass'
    | '/huddle'
    | '/lock'
    | '/login'
    | '/sitemap.xml'
    | '/team'
    | '/api/chat'
    | '/vouch/$voteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BreakGlassRoute: typeof BreakGlassRoute
  HuddleRoute: typeof HuddleRoute
  LockRoute: typeof LockRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  ApiChatRoute: typeof ApiChatRoute
  VouchVoteIdRoute: typeof VouchVoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huddle': {
      id: '/huddle'
      path: '/huddle'
      fullPath: '/huddle'
      preLoaderRoute: typeof HuddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/break-glass': {
      id: '/break-glass'
      path: '/break-glass'
      fullPath: '/break-glass'
      preLoaderRoute: typeof BreakGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vouch/$voteId': {
      id: '/vouch/$voteId'
      path: '/vouch/$voteId'
      fullPath: '/vouch/$voteId'
      preLoaderRoute: typeof VouchVoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BreakGlassRoute: BreakGlassRoute,
  HuddleRoute: HuddleRoute,
  LockRoute: LockRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  ApiChatRoute: ApiChatRoute,
  VouchVoteIdRoute: VouchVoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
